name: trail4x4
description: "Application GPS 4x4"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  gpx: ^2.2.0
  http: ^1.2.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.0
  sensors_plus: ^7.0.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.0
  wakelock_plus: ^1.4.0
  file_picker: ^10.3.10
  flutter_map_cache: ^1.5.2
  dio_cache_interceptor_hive_store: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
